# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-09 08:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_auto_20181009_0642'),
        ('profiles', '0002_auto_20181005_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='academic.Course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='academic.Department'),
            preserve_default=False,
        ),
    ]
