# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-08 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='academic.Subject'),
            preserve_default=False,
        ),
    ]
