# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-09 05:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_auto_20181009_0456'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='exam',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='academic.Exam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessment',
            name='roll_no',
            field=models.IntegerField(default=None, editable=False),
            preserve_default=False,
        ),
    ]
