# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-09 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_remove_exam_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='status',
            field=models.CharField(choices=[('Failed', 'Failed'), ('Passed', 'Passed')], default=None, editable=False, max_length=5),
            preserve_default=False,
        ),
    ]
