# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-09 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_assessment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='status',
            field=models.CharField(choices=[('Failed', 'Failed'), ('Passed', 'Passed')], editable=False, max_length=6),
        ),
    ]
